### ISSUE TITLE
Locations update and customer notice

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_GENFINPLAN#5]
I don't have a repo for the old ESI website so I'm making it here. That old site needs to have an address updated and also some kind of notice created which directs people to GFP. Ping me for more details.

**Comment by d4mation** [comment]
All set on http://eriksmithinvestments.com/

**Comment by brashrebel** [comment]
Reopening because I was wrong about something. New address is:

977 Airport Rd, Jackson, MI. 49202

and phone number is 517-795-2025. My bad.

**Comment by d4mation** [comment]
Fixed 👍
