### ISSUE TITLE
Adjust contact page to accommodate second location

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_GENFINPLAN#7]
Generations has two locations: Jackson and Battle Creek. They want the contact page, at least the part above the form, to have two columns, one for each. They will both have a rotating image gallery like what is there now and they must have easy control over the images in the gallery.

**Comment by d4mation** [comment]
Copied my comments from Slack so I can find it later:

>As I’m understanding it, we would be restructuring the entire page at that point. Looking at the template file for that page, WooThemes has it pulling everything in via the Theme Options outside of that Slider (which is the only thing they’ve added to the page themselves).
>
>We could go about it the “WooThemes way” (AKA the wrong way :stuck_out_tongue_closed_eyes: ) and add extra things to the Theme Options to try to keep things as similar to manage as they are now as we reasonably can. That would take longer simply due to having to wrap our heads around that methodology and trying to find a way to make everything fit on the page how they want it so that it makes sense to both them and to us.
>
>Or we throw all that out and make everything within that page _actually managed_ within that page’s Edit screen. At this point we’d only really save the contact form and we’d be recreating the rest of it. This would be faster (and better to manage moving forward), but it would potentially need retraining with the Client and could possibly be the only part of the site done _right_ and could actually end up being unfortunately confusing as WooThemes likely has their own methods to manage content strewn throughout the page templates used on the site.
>
>Either way the Theme kind of backs us into a corner. It seems like a simple change, but the way the code is structured it would unfortunately take some time either way. I don’t know if I could give an exact time estimate, but it makes my skin crawl thinking about it to be honest. :mask:

**Comment by brashrebel** [comment]
Go with the second route and re-engineer the page. Throw out the old contact form and use a Gravity Form instead. Put in some nice custom fields on the contact page or something, or if it is more convenient, continue using the Theme Options values for locations since that info might be used in other places on the site. But yeah, go ahead and completely replace the Contact Form page template that is in use now.

**Comment by d4mation** [comment]
Two locations, two sliders, one map, Gravity Forms Form.

![image](https://cloud.githubusercontent.com/assets/7770631/21555143/6855634a-cde3-11e6-930f-84f99ecc700b.png)

**Comment by d4mation** [comment]
Don't know why the second marker isn't in that screenshot. It is there:

![image](https://cloud.githubusercontent.com/assets/7770631/21555215/fd40e8c6-cde3-11e6-9c28-36fac19d2fb9.png)
